config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "home#index"
   get  '/about', to: 'pages#about'
   get  '/products', to: 'products#index'
   get  '/products/show/:id', to: 'products#show'
   get  '/posters', to: 'products#poster'
   get  '/illustrations', to: 'products#illustration'
   get  '/woodblocks', to: 'products#woodblock'
   get '/search' => 'products#search'
  # namespace for admin routes
  namespace :admin do
    # admin dashboard route
    get 'dashboard', to: 'dashboard#home' 
    resources :products
    resources :orders
    resources :categories
    resources :users
    resources :product
    resources :variants
  end
  

end




  

app/models/order.rb
class Order < ApplicationRecord
    validates :order_number, :total_price, :delivery_address, :payment_method, :status, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @orders = Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
     @order = Order.find(params[:id])
  end

  # GET /admin/orders/new
  def new
    @order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
    @order = Order.find(params[:id])
    # @user = User.find(params[:Order.user_id])
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @order = Order.new(admin_order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @order.update(admin_order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/edit.html.erb
<% content_for :title, "Edit order"  %>

<div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Edit Order [Order Number]</h4>
                  <p class="card-description">
                    Use the form below to edit information about an order
                  </p>
                  <form class="forms-sample">
                    <div class="form-group">
                      <label for="name">Name</label>
                      <input type="text" class="form-control" id="name" placeholder="Name" value="To Be Completed" disabled>
                    </div>
                    
                    <div class="form-group">
                        <div class="card">
                <div class="card-body">
                  <h5 class="card-title mb-4">Manage Order Items</h5>
                  <div class="fluid-container">
                    <div class="row ticket-card mt-3 pb-2 border-bottom pb-3 mb-3">
                      <div class="col-md-1">
                         <%= image_tag 'faces/face1', class: 'img-sm rounded-circle mb-4 mb-md-0' %>
                      </div>
                      <div class="ticket-details col-md-9">
                        <div class="d-flex">
                          <p class="text-dark font-weight-semibold mr-2 mb-0 no-wrap">Item Name</p>
                          <p class="text-primary mr-1 mb-0">[Variant]</p>
                          <p class="text-primary mr-1 mb-0">[€0.00]</p>
                        </div>
                        <p class="text-gray ellipsis mb-2">Item Description
                        </p>
                        <div class="row text-gray d-md-flex d-none">
                          <div class="col-4 d-flex">
                            <small class="mb-0 mr-2 text-muted text-muted">Quantity: </small>
                            <small class="Last-responded mr-2 mb-0 text-muted text-muted">1</small>
                          </div>
                          <div class="col-4 d-flex">
                            <small class="mb-0 mr-2 text-muted text-muted">Total Price :</small>
                            <small class="Last-responded mr-2 mb-0 text-muted text-muted">€0.00</small>
                          </div>
                        </div>
                      </div>
                      <div class="ticket-actions col-md-2">
                        <div class="btn-group dropdown">
                          <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">
                              <i class="fa fa-reply fa-fw"></i>Remove From Order
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                    </div>
                    
                    <div class="form-group">
                      <label for="note">Note</label>
                      <textarea class="form-control" id="note" rows="20" disabled><%=  %></textarea>
                    </div>
                    <div class="form-group">
                        <label for="total_price">Total Price</label>
                        <div class="input-group">
                          <div class="input-group-prepend bg-primary border-primary">
                            <span class="input-group-text bg-transparent text-white">€</span>
                          </div>
                          <input type="text" class="form-control" id="total_price" value="<%= %>">
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="delivery_address">Delivery Address</label>
                      <input type="text" class="form-control" id="delivery_address" placeholder="Delivery Address" value="<%=  %>">
                    </div>
                    <div class="form-group">
                    <label for="status">Status</label>
                    <select class="form-control" id="status">
                      <option><%=  %></option>
                    </select>
                  </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>

app/views/admin/orders/index.html.erb
<% content_for :title, "Orders"  %>

<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <%= link_to "Add Order", new_admin_order_path, class: "btn btn-outline-primary float-right" %>
                   <h4 class="card-title">Orders List</h4>
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            Order Number
                          </th>
                          <th>
                            Name
                          </th>
                          <th>
                            Status
                          </th>
                          <th>
                            Total Price
                          </th>
                          <th>
                            Created 
                          </th>
                           <th>
                            Link
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @orders.each do |order| %>
                              <tr>
                                <td>
                                  <%= order.order_number %>
                                </td>
                                <td>
                                  Order Name(TBC)
                                </td>
                                <td>
                                  <%= order.status %>
                                </td>
                                <td>
                                  €<%= order.total_price %>
                                </td>
                                <td>
                                  <%= order.created_at.strftime("%b %e, %Y") %>
                                </td>
                                <td>
                                  <%= link_to admin_order_path(order.id)  do %>
                                  View
                                  <% end %>
                                </td>
                            </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

app/views/admin/orders/show.html.erb
<% content_for :title, "Order"  %>

<div class="row">
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Order Details</h4>
                  <h5>Name</h5>
                  <p>{User Name}</p>
                  <h5>Order Number</h5>
                  <p><%= @order.order_number %></p>
                  <h5>Delivery Address</h5>
                  <p><%= @order.delivery_address %></p>
                  <h5>Payment Method</h5>
                  <p><%= @order.payment_method %></p>
                  <h5>Date</h5>
                  <p><%= @order.created_at.strftime("%b %e, %Y") %></p>
                  <h5>Note</h5>
                  <p><%= @order.note %></p>
                </div>
              </div>
            </div>
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Order Items</h4>
                  <h5>{product name}</h5>
                  <p>{product variant - if applicable}</p>
                  <p>{Product Quantity}</p>
                  <p>{product price}</p>
                  
                  <h5>€<%= @order.total_price %></h5></h5>
                </div>
              </div>
            </div>
          </div>