config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "home#index"
   get  '/about', to: 'pages#about'
   get  '/products', to: 'products#index'
   get  '/products/show/:id', to: 'products#show'
   get  '/posters', to: 'products#poster'
   get  '/illustrations', to: 'products#illustration'
   get  '/woodblocks', to: 'products#woodblock'
   get '/search' => 'products#search'
  # namespace for admin routes
  namespace :admin do
    # admin dashboard route
    get 'dashboard', to: 'dashboard#home' 
    resources :products
    resources :orders
    resources :categories
    resources :users
    resources :product
    resources :variants
  end
  

end




  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # field validation
    validates :name, presence: true
    
    # association with products through our join table product_categories
    has_many :product_categories
    has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
    validates :order_number, :total_price, :delivery_address, :payment_method, :status, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    # field validation
    validates :name, presence: true, length: {minimum: 5, maximum:50}
    validates :description, presence: true, length: {minimum: 10, maximum:300}
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates :stock, presence: true, numericality: { greater_than: 0 }
    validates :image, presence: true
    
    # association with categories through our join table product_categories
    has_many :product_categories, dependent: :delete_all
    has_many :categories, through: :product_categories

    # association with variants through our join table product_variants
    has_many :product_variants, dependent: :delete_all
    has_many :variants, through: :product_variants

	def self.search(pattern, id)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      where('name LIKE ? or description LIKE ? or artist_name LIKE ?', "%#{pattern}%", "%#{pattern}%", "%#{pattern}%")
    end
    end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
  belongs_to :variant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :confirmable,:registerable,
         :recoverable, :rememberable, :validatable

end

app/models/variant.rb
class Variant < ApplicationRecord
    # field validation
    validates :name, presence: true
    validates :option, presence: true
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates :stock, presence: true, numericality: { greater_than: 0 }
    validates :image, presence: true

    # association with products through our join table product_variants
    has_many :product_variants
    has_many :variants, through: :product_variants
end

app/controllers/admin/base_controller.rb
# Inherit directly from ActionController::Base rather than ApplicationController to ensure clean separation
class Admin::BaseController < ActionController::Base
    protect_from_forgery
    
    # use an admin-specific layout instead of the main application layout
    layout "admin"
    
    # all child controllers will automatically enforce access to admins only
   # before_action :require_admin
    
  #  def require_admin
        # ...
  #  end

	before_action :ensure_admin_user!
	def ensure_admin_user!
	unless current_user and current_user.admin?
	redirect_to root_path
	end
	end



end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    def home
        # @products = Product.all 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
   #for edit user to work/use .for for older ruby versions and .permit for newer
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname,:lastname, :email, :password, :current_password) }
        end

	add_flash_types :danger, :info, :warning, :success
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    #sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @category = Category.all
  @products = Product.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pages
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all
@productCount = Product.all.count
end

def show
 @singleitem = Product.find(params[:id])
 variants = ProductVariant.where('product_id = ?', params[:id])
 @variantsItem=[]
for item in variants
	var = Variant.find(item.variant_id)
	@variantsItem.push(var)
end
end

def poster
productsID = ProductCategory.select("product_id").where("category_id = 1")
general(productsID)
category = Category.first
@header = category.name
end

def illustration
productsID = ProductCategory.select("product_id").where("category_id = 2")
general(productsID)
category = Category.second
@header = category.name
end

def woodblock
productsID = ProductCategory.select("product_id").where("category_id = 3")
general(productsID)
category = Category.third
@header = category.name
end

def general(productsID)
@productItem=[]
for item in productsID
	product = Product.find(item.product_id)
	@productItem.push(product)

end
end

def search

 @searchProducts = Product.search(params[:q], params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @searchProducts }
    end
@productsFromSearch = @searchProducts.count
if @productsFromSearch==0
redirect_to search_path, info: "No items match this search, try searching by category or browse through the products below"
end
end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include FontAwesome::Rails::IconHelper
    
    # helper to set the page title within the page view
	 def title(page_title)
        content_for(:title) { page_title }
     end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/dashboard/partials/_nav.html.erb
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html">
          <%= image_tag('logo') %>
        </a>
        <a class="navbar-brand brand-logo-mini" href="index.html">
          <%= image_tag('logo-mini') %>
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text">Hello, Richard V.Welsh !</span>
              <%= image_tag('faces/face1', class:'img-xs rounded-circle') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a>
              <%= link_to 'Manage Accounts', admin_orders_path, class: "dropdown-item" %>
              <a class="dropdown-item">
                Sign Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

app/views/admin/dashboard/partials/_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <div class="nav-link">
                <div class="user-wrapper">
                    <div class="profile-image">
                        <%= image_tag('faces/face1') %>
                    </div>
                    <div class="text-wrapper">
                        <p class="profile-name">{user name}</p>
                        <div>
                            <small class="designation text-muted">Administrator</small>
                            <span class="status-indicator online"></span>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <li class="nav-item">
            <%= link_to admin_dashboard_path, class: "nav-link" do %>
            <i class="menu-icon mdi mdi-television"></i>
            <span class="menu-title">Dashboard</span>
            <% end %>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#products" aria-expanded="false" aria-controls="ui-basic">
                <i class="menu-icon mdi mdi-content-copy"></i>
                <span class="menu-title">Products</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="products">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <%= link_to "Index", admin_products_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Add Product", new_admin_product_path, class: "nav-link" %>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#categories" aria-expanded="false" aria-controls="ui-basic">
                <i class="menu-icon mdi mdi-content-copy"></i>
                <span class="menu-title">Categories</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="categories">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <%= link_to "Index", admin_categories_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Add Category", new_admin_category_path, class: "nav-link" %>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#variants" aria-expanded="false" aria-controls="ui-basic">
                <i class="menu-icon mdi mdi-content-copy"></i>
                <span class="menu-title">Variants</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="variants">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <%= link_to "Index", admin_variants_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Add Variant", new_admin_variant_path, class: "nav-link" %>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#orders" aria-expanded="false" aria-controls="ui-basic">
                <i class="menu-icon mdi mdi-content-copy"></i>
                <span class="menu-title">Orders</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="orders">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <%= link_to "Index", admin_orders_path, class: "nav-link" %>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="pages/forms/basic_elements.html">
                <i class="menu-icon mdi mdi-backup-restore"></i>
                <span class="menu-title">Form elements</span>
            </a>
        </li>
    </ul>
</nav>