config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "home#index"
   get  '/about', to: 'pages#about'
   get  '/products', to: 'products#index'
   get  '/products/show/:id', to: 'products#show'
   get  '/posters', to: 'products#poster'
   get  '/illustrations', to: 'products#illustration'
   get  '/woodblocks', to: 'products#woodblock'
   get '/search' => 'products#search'
  # namespace for admin routes
  namespace :admin do
    # admin dashboard route
    get 'dashboard', to: 'dashboard#home' 
    resources :products
    resources :orders
    resources :categories
    resources :users
    resources :product
    resources :variants
  end
  

end




  

app/models/product.rb
class Product < ApplicationRecord
    # field validation
    validates :name, presence: true, length: {minimum: 5, maximum:50}
    validates :description, presence: true, length: {minimum: 10, maximum:300}
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates :stock, presence: true, numericality: { greater_than: 0 }
    validates :image, presence: true
    
    # association with categories through our join table product_categories
    has_many :product_categories, dependent: :delete_all
    has_many :categories, through: :product_categories

    # association with variants through our join table product_variants
    has_many :product_variants, dependent: :delete_all
    has_many :variants, through: :product_variants

	def self.search(pattern, id)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      where('name LIKE ? or description LIKE ? or artist_name LIKE ?', "%#{pattern}%", "%#{pattern}%", "%#{pattern}%")
    end
    end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::BaseController
  def index
    @products = Product.all
  end

  def create
    # render plain: params[:product].inspect
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product was successfully created'
      redirect_to edit_admin_product_path(@product)
    else
      render 'new'
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product was successfully updated'
      redirect_to edit_admin_product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product was successfully deleted"
    redirect_to admin_products_path
  end

  private

  # define the product_params
  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :image, :artist_name, :sku, category_ids: [], variant_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all
@productCount = Product.all.count
end

def show
 @singleitem = Product.find(params[:id])
 variants = ProductVariant.where('product_id = ?', params[:id])
 @variantsItem=[]
for item in variants
	var = Variant.find(item.variant_id)
	@variantsItem.push(var)
end
end

def poster
productsID = ProductCategory.select("product_id").where("category_id = 1")
general(productsID)
category = Category.first
@header = category.name
end

def illustration
productsID = ProductCategory.select("product_id").where("category_id = 2")
general(productsID)
category = Category.second
@header = category.name
end

def woodblock
productsID = ProductCategory.select("product_id").where("category_id = 3")
general(productsID)
category = Category.third
@header = category.name
end

def general(productsID)
@productItem=[]
for item in productsID
	product = Product.find(item.product_id)
	@productItem.push(product)

end
end

def search

 @searchProducts = Product.search(params[:q], params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @searchProducts }
    end
@productsFromSearch = @searchProducts.count
if @productsFromSearch==0
redirect_to search_path, info: "No items match this search, try searching by category or browse through the products below"
end
end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<% content_for :title, "Edit " + @product.name %>
<div class="col-md-6 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">
        Edit
        <%= @product.name %>
      </h4>
      <p class="card-description">
        Use the form below to edit information about the
        <%= @product.name %>
      </p>
      <%= form_for [:admin, @product], class: "forms-sample" do |f| %>
      <%= render "admin/products/partials/form", :f => f %>
      <% end %>
    </div>
  </div>

  <%= render "admin/products/partials/errors" %>
</div>

app/views/admin/products/index.html.erb
<% content_for :title, "Products" %>

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <%= link_to "Add Product", new_admin_product_path, class: "btn btn-outline-primary float-right" %>
      <h4 class="card-title">Products List</h4>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                Preview
              </th>
              <th>
                Name
              </th>
              <th>
                Stock
              </th>
              <th>
                Price
              </th>
              <th>
                Categories
              </th>
              <th>
                Date Published
              </th>
              <th>
                Link
              </th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
            <tr>
              <td>
                <% if product.image.blank? %>
                <%= image_tag product.image %>
                <% else %>
                <%= image_tag "https://image.jimcdn.com/app/cms/image/transf/none/path/s8e84ffc7090a5bd2/image/i9eed849b0f18dd36/version/1534159621/image.png" %>
                <% end %>
              </td>
              <td>
                <%= product.name %>
              </td>
              <td>
                <%= product.stock %>
              </td>
              <td>
                €
                <%= product.price %>
              </td>
              <td>
                <% product.categories.each do |category| %>
                <%= link_to category.name, edit_admin_category_path(category) %>
                <br>
                <% end %>
              </td>
              <td>
                <%= product.created_at.strftime("%b %e, %Y") %>
              </td>
              <td>
                <%= link_to 'Edit', edit_admin_product_path(product) %> |
                <%= link_to 'Delete', admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% content_for :title, "Create new product" %>
<div class="row">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Add Product</h4>
        <p class="card-description">
          Use the form below to add information about the product
        </p>
        <%= form_for [:admin, @product], class: "forms-sample" do |f| %>
        <%= render "admin/products/partials/form", :f => f %>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "admin/products/partials/errors" %>
</div>