config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "home#index"
   get  '/about', to: 'pages#about'
   get  '/products', to: 'products#index'
   get  '/products/show/:id', to: 'products#show'
   get  '/posters', to: 'products#poster'
   get  '/illustrations', to: 'products#illustration'
   get  '/woodblocks', to: 'products#woodblock'
   get '/search' => 'products#search'
  # namespace for admin routes
  namespace :admin do
    # admin dashboard route
    get 'dashboard', to: 'dashboard#home' 
    resources :products
    resources :orders
    resources :categories
    resources :users
    resources :product
    resources :variants
  end
  

end




  

app/models/product.rb
class Product < ApplicationRecord
    # field validation
    validates :name, presence: true, length: {minimum: 5, maximum:50}
    validates :description, presence: true, length: {minimum: 10, maximum:300}
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates :stock, presence: true, numericality: { greater_than: 0 }
    validates :image, presence: true
    
    # association with categories through our join table product_categories
    has_many :product_categories, dependent: :delete_all
    has_many :categories, through: :product_categories

    # association with variants through our join table product_variants
    has_many :product_variants, dependent: :delete_all
    has_many :variants, through: :product_variants

	def self.search(pattern, id)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      where('name LIKE ? or description LIKE ? or artist_name LIKE ?', "%#{pattern}%", "%#{pattern}%", "%#{pattern}%")
    end
    end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::BaseController
  def index
    @products = Product.all
  end

  def create
    # render plain: params[:product].inspect
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product was successfully created'
      redirect_to edit_admin_product_path(@product)
    else
      render 'new'
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product was successfully updated'
      redirect_to edit_admin_product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product was successfully deleted"
    redirect_to admin_products_path
  end

  private

  # define the product_params
  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :image, :artist_name, :sku, category_ids: [], variant_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all
@productCount = Product.all.count
end

def show
 @singleitem = Product.find(params[:id])
 variants = ProductVariant.where('product_id = ?', params[:id])
 @variantsItem=[]
for item in variants
	var = Variant.find(item.variant_id)
	@variantsItem.push(var)
end
end

def poster
productsID = ProductCategory.select("product_id").where("category_id = 1")
general(productsID)
category = Category.first
@header = category.name
end

def illustration
productsID = ProductCategory.select("product_id").where("category_id = 2")
general(productsID)
category = Category.second
@header = category.name
end

def woodblock
productsID = ProductCategory.select("product_id").where("category_id = 3")
general(productsID)
category = Category.third
@header = category.name
end

def general(productsID)
@productItem=[]
for item in productsID
	product = Product.find(item.product_id)
	@productItem.push(product)

end
end

def search

 @searchProducts = Product.search(params[:q], params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @searchProducts }
    end
@productsFromSearch = @searchProducts.count
if @productsFromSearch==0
redirect_to search_path, info: "No items match this search, try searching by category or browse through the products below"
end
end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/illustration.html.erb
<% content_for :title, @header %>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2><%=@header%></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- product count -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="section-padding-50">
  <div class="container">
    <div class="row">
            <!-- Total Products -->
            <div style ="display:block; text-transform:uppercase; padding-left:2.5%">
                <span>
                  <%=@productItem.count %> illustrations found
                  </span>
                </div>

      <hr style ="display:block; height:1px; width:100%;"/>
            <h4 class="mb-20" style ="display:block;padding-left:2.5%">Catagories</h4>
            <!--  Catagories  -->
              <ul class="categories_container mb-10" style="padding-left:0rem; padding-left:2.5%">
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 0;">
                  <%= link_to "All", products_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Posters", posters_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Illustrations", illustrations_path%>
                 </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Woodblock Prints", woodblocks_path%>
                </li>
              </ul>

        <div class="shop_grid_product_area">
<%@productItem.each do |item|%>
            <!-- Single Product -->
              <ul style="display:inline-block; width:24%; max height:440px; padding-left:0rem; padding:2.5%">
                <!-- Product Image -->
                <li><div class="product-img">
                    <%= image_tag item.image%>
                    </div>
                </li>
                <!-- Product Description -->
                <li>
                <div class="product-description">
                  <a href="/products/show/<%=item.id%>">learn more >></a>
                    <h6 style ="margin-bottom:0px"><%=item.name%></h6>
                  </a>
                  <p class="product-price" style ="margin-bottom:5px;">
                     &euro; <%=item.price%>
                  </p>
                  <!-- Hover Content -->
                  <div class="hover-content">
                    <!-- Add to Cart -->
                    <div class="add-to-cart-btn">
                      <a href="#" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px;">Add to Cart</a>
                    </div>
                  </div>
                </div>
                </li>
              </ul>

        <%end%>   
          </div>
     
    </div>
    </div>  
</section>
<!-- ##### Shop Grid Area End ##### -->

app/views/products/index.html.erb
<% content_for :title, "Products" %>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2>Products</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- product count -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="section-padding-50">
  <div class="container">
    <div class="row">
            <!-- Total Products -->
            <div style ="display:block; text-transform:uppercase; padding-left:2.5%">
                <span>
                  <%=@productCount %> products found
                  </span>
                </div>

      <hr style ="display:block; height:1px; width:100%;"/>
            <h4 class="mb-20" style ="display:block;padding-left:2.5%">Catagories</h4>
      <!--  Catagories  -->
      <ul class="categories_container mb-10" style="padding-left:0rem; padding-left:2.5%">
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 0;">
          <%= link_to "All", products_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Posters", posters_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Illustrations", illustrations_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Woodblock Prints", woodblocks_path%>
        </li>
      </ul>

        <div class="shop_grid_product_area">
<%@products.each do |product|%>
            <!-- Single Product -->
              <ul style="display:inline-block; width:24%; max height:440px; padding-left:0rem; padding:2.5%">
                <!-- Product Image -->
                <li><div class="product-img">
                    <%= image_tag product.image%>
                    </div>
                </li>
                <!-- Product Description -->
                <li>
                <div class="product-description">
                  <a href="/products/show/<%=product.id%>">learn more >></a>
                    <h6 style ="margin-bottom:0px"><%=product.name%></h6>
                  </a>
                  <p class="product-price" style ="margin-bottom:5px;">
                      <%=product.price%>
                  </p>
                  <!-- Hover Content -->
                  <div class="hover-content">
                    <!-- Add to Cart -->
                    <div class="add-to-cart-btn">
                      <a href="#" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px;">Add to Cart</a>
                    </div>
                  </div>
                </div>
                </li>
              </ul>

        <%end%>   
          </div>
        <!-- Pagination -->
    </div>
    </div>  
</section>
<!-- ##### Shop Grid Area End ##### -->

app/views/products/poster.html.erb
<% content_for :title, @header %>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2><%=@header%></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- product count -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="section-padding-50">
  <div class="container">
    <div class="row">
            <!-- Total Products -->
            <div style ="display:block; text-transform:uppercase; padding-left:2.5%">
                <span>
                  <%=@productItem.count %> posters found
                  </span>
                </div>

      <hr style ="display:block; height:1px; width:100%;"/>
            <h4 class="mb-20" style ="display:block;padding-left:2.5%">Catagories</h4>
            <!--  Catagories  -->
              <ul class="categories_container mb-10" style="padding-left:0rem; padding-left:2.5%">
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 0;">
                  <%= link_to "All", products_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Posters", posters_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Illustrations", illustrations_path%>
                 </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Woodblock Prints", woodblocks_path%>
                </li>
              </ul>

        <div class="shop_grid_product_area">
<%@productItem.each do |item|%>
            <!-- Single Product -->
              <ul style="display:inline-block; width:24%; max height:440px; padding-left:0rem; padding:2.5%">
                <!-- Product Image -->
                <li><div class="product-img">
                    <%= image_tag item.image%>
                    </div>
                </li>
                <!-- Product Description -->
                <li>
                <div class="product-description">
                  <a href="/products/show/<%=item.id%>">learn more >></a>
                    <h6 style ="margin-bottom:0px"><%=item.name%></h6>
                  </a>
                  <p class="product-price" style ="margin-bottom:5px;">
                    &euro; <%=item.price%>
                  </p>
                  <!-- Hover Content -->
                  <div class="hover-content">
                    <!-- Add to Cart -->
                    <div class="add-to-cart-btn">
                      <a href="#" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px;">Add to Cart</a>
                    </div>
                  </div>
                </div>
                </li>
              </ul>

        <%end%>   
          </div>
     
    </div>
    </div>  
</section>
<!-- ##### Shop Grid Area End ##### -->

app/views/products/search.html.erb
<% content_for :title, "Products" %>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2>Products</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<%= render 'layouts/flash_messages' %>
<!-- product count -->
<!-- ##### Shop Grid Area Start ##### -->
<section class="section-padding-50">
  <div class="container">
    <div class="row">
            <!-- Total Products -->
            <div style ="display:block; text-transform:uppercase; padding-left:2.5%">
                <span>
                  <%=@productsFromSearch %> products found
                  </span>
                </div>

      <hr style ="display:block; height:1px; width:100%;"/>
            <h4 class="mb-20" style ="display:block;padding-left:2.5%">Catagories</h4>
      <!--  Catagories  -->
      <ul class="categories_container mb-10" style="padding-left:0rem; padding-left:2.5%">
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 0;">
          <%= link_to "All", products_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Posters", posters_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Illustrations", illustrations_path%>
        </li>
        <!-- Single Item -->
        <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
          <%= link_to "Woodblock Prints", woodblocks_path%>
        </li>
      </ul>
	  
        <div class="shop_grid_product_area">

<%@searchProducts.each do |product|%>
            <!-- Single Product -->
              <ul style="display:inline-block; width:24%; max height:440px; padding-left:0rem; padding:2.5%">
                <!-- Product Image -->
                <li><div class="product-img">
                    <%= image_tag product.image%>
                    </div>
                </li>
                <!-- Product Description -->
                <li>
                <div class="product-description">
                  <a href="/products/show/<%=product.id%>">learn more >></a>
                    <h6 style ="margin-bottom:0px"><%=product.name%></h6>
                  </a>
                  <p class="product-price" style ="margin-bottom:5px;">
                     <!-- <%=product.price%>-->
                  </p>
                  <!-- Hover Content -->
                  <div class="hover-content">
                    <!-- Add to Cart -->
                    <div class="add-to-cart-btn">
                      <a href="#" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px;">Add to Cart</a>
                    </div>
                  </div>
                </div>
                </li>
              </ul>

        <%end%>   
          </div>
        <!-- Pagination -->
    </div>
    </div>  
</section>
<!-- ##### Shop Grid Area End ##### -->

app/views/products/show.html.erb
<% content_for :title, @singleitem.name %>
<div class="breadcumb_area bg-img" >
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2><%=@singleitem.name%></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container clearfix mb-30" style="padding-bottom:20px;">
 <!-- Single Product Thumb -->
        <div class="single_product_thumb clearfix" style = "width:45%; float:left;">
            <div class="product_image">

                <%= image_tag @singleitem.image%>

            </div>
		</div>

 <!-- ##### Single Product Details Area Start ##### -->
    <section class="single_product_details_area d-flex align-items-center" style = "width:50%; float:right;">
        <!-- Single Product Description -->
        <div class="single_product_desc clearfix">
            <span><%=@singleitem.artist_name%></span>
            <a href="cart.html">
                <h2><%=@singleitem.name%></h2>
            </a>
            <p class="product-price"> &euro;<%=@singleitem.price%></p>
            <p class="product-desc"><%=@singleitem.description%></p>

            <!-- Form -->
            <form class="cart-form clearfix" method="post">
                <!-- Select Box -->
                <div class="select-box d-flex mt-50 mb-30">
                    <select name="select" id="productMaterial" class="mr-5">
					<% @variantsItem.each do |v|%>
                        <option value=<%= v.name %>><%=v.option%>&nbsp; &euro;<%=v.price%><h2></option>
                    <%end%>
                    </select>
                  
                </div>
                <!-- Cart & Favourite Box -->
                <div class="cart-fav-box d-flex align-items-center">
                    <!-- Cart -->
                    <button type="submit" name="addtocart" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px; background-color:white;">Add to Cart</button>
                </div>
            </form>
        </div>
    </section>
</div>
    <!-- ##### Single Product Details Area End ##### -->

app/views/products/woodblock.html.erb
<% content_for :title, @header %>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="page-title text-center">
          <h2>Woodblock Prints</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- product count -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="section-padding-50">
  <div class="container">
    <div class="row">
            <!-- Total Products -->
            <div style ="display:block; text-transform:uppercase; padding-left:2.5%">
                <span>
                  <%=@productItem.count %> woodblock prints found
                  </span>
                </div>

      <hr style ="display:block; height:1px; width:100%;"/>
            <h4 class="mb-20" style ="display:block;padding-left:2.5%">Catagories</h4>
            <!--  Catagories  -->
              <ul class="categories_container mb-10" style="padding-left:0rem; padding-left:2.5%">
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 0;">
                  <%= link_to "All", products_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Posters", posters_path%>
                </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Illustrations", illustrations_path%>
                 </li>
                <!-- Single Item -->
                <li style =" display: inline-block; float:left; padding: 0 10px 0 10px;">
                  <%= link_to "Woodblock Prints", woodblocks_path%>
                </li>
              </ul>

        <div class="shop_grid_product_area">
<%@productItem.each do |item|%>
            <!-- Single Product -->
              <ul style="display:inline-block; width:24%; max height:440px; padding-left:0rem; padding:2.5%">
                <!-- Product Image -->
                <li><div class="product-img">
                    <%= image_tag item.image%>
                    </div>
                </li>
                <!-- Product Description -->
                <li>
                <div class="product-description">
                  <a href="/products/show/<%=item.id%>">learn more >></a>
                    <h6 style ="margin-bottom:0px"><%=item.name%></h6>
                  </a>
                  <p class="product-price" style ="margin-bottom:5px;">
                    &euro; <%=item.price%>
                  </p>
                  <!-- Hover Content -->
                  <div class="hover-content">
                    <!-- Add to Cart -->
                    <div class="add-to-cart-btn">
                      <a href="#" class="btn btn-block" style="border:1px solid black; margin-bottom: 10px;">Add to Cart</a>
                    </div>
                  </div>
                </div>
                </li>
              </ul>

        <%end%>   
          </div>
     
    </div>
    </div>  
</section>
<!-- ##### Shop Grid Area End ##### -->